In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
spam_df = pd.read_csv("spam.csv")
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [3]:
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [4]:
spam_df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [5]:
x_train, x_test, y_train, y_test = train_test_split(spam_df.Message, spam_df.spam, test_size = 0.25)

In [6]:
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [7]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [9]:
email_ham = ['Hii how are you']
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

In [10]:
email_spam = ['reward click on the link']
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

In [11]:
x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9856424982053122

In [12]:
def classify_email():
    input_mail = [email_entry.get('1.0', 'end-1c')]
    input_data = cv.transform(input_mail)
    prediction = model.predict(input_data)
    result = 'Spam' if prediction[0] == 1 else "Not Spam"
    messagebox.showinfo("Result", f"The Email is Classified as: {result}")
    
# input_mail = [input()]


# if prediction[0] == 1:
#     print("Spam")
# else:
#     print("Ham")

In [14]:
import tkinter as tk
from tkinter import messagebox
root = tk.Tk()
root.title("Email Spam Detector")


''

In [15]:
email_label = tk.Label(root, text='Enter Email Content:')
email_label.pack()
email_entry = tk.Text(root, height = 10, width = 50)
email_entry.pack()

classify_button = tk.Button(root, text='Classify Email', command=classify_email)
classify_button.pack()

root.mainloop()

In [1]:
#from googleapiclient.discovery import build
#from google.oauth2.credentials import Credentials
#from google_auth_oauthlib.flow import InstalledAppFlow
#from google.auth.transport.requests import Request
#import base64
#from email import message_from_bytes


In [2]:
#def gmail_login():
 #   scopes = ['https://www.googleapis.com/auth/gmail.readonly']
  #  creds = None
   # if creds and creds.expired and creds.refresh_token:
    #    creds.refresh(Request())
    #else:
     #   flow = InstalledAppFlow.from_client_secrets_file('client_secret_1.json', scopes)
      #  creds = flow.run_local_server(port=0)
        
    #services = build('gmail', 'v1', credentials=creds)
    #return services

In [3]:
#def fetch_emails(services):
 #   results = services.users().messages().list(userId='me').execute()
 #   messages = results.get('messages', [])
    
 #   for message in messages[:10]:
 #       msg = services.users().messages().get(userId='me', id=message['id'], format='raw').execute()
 #       msg_str = base64.urlsafe_b64decode(msg['raw'].encode('ASCII'))
 #       mine_msg = message_from_bytes(msg_str)

 #       if mine_msg.is_multipart():
 #           for part in mine_msg.walk():
 #               content_type = part.get_content_type()
 #               if content_type == 'text/plain':
 #                   email_body = part.get_payload(decode=True).decode('utf-8')
 #                   break
 #       else:
 #           email_body = mine_msg.get_payload(decode=True).decode('utf-8')
        
 #       if email_body:
 #           input_data = cv.transform([email_body])
 #           prediction = model.predict(input_data)
 #           result = 'Spam' if prediction[0] == 1 else "Not Spam"

 #           messagebox.showinfo("Result", f"The Email is Classified as: {result}\n\nEmail Content:\n{email_body}")
 #       else:
 #           messagebox.showerror("Error", "Could not extract email content.")


In [4]:
#services = gmail_login()
#fetch_emails(services)